name = "LandEnginesPredict"
uuid = "1e02c578-1fa9-4e3b-8e1d-f93235db8ca2"
authors = ["Raimundo Vial"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
